[package]
name = "scli"
version = "0.2.4"
authors = ["Ziyang Li <liby99@icloud.com>"]
edition = "2018"

[dependencies]
scallop-core = { path = "../../core" }
structopt = "0.3"

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
