[package]
name = "sclc-core"
version = "0.1.9"
authors = ["Ziyang Li <liby99@icloud.com>"]
edition = "2018"

[dependencies]
scallop-core = { path = "../../core" }
structopt = "0.3"
proc-macro2 = "1.0"
quote = "1.0"

[dev-dependencies]
tempfile = "3.3"
