[package]
name = "scallop-wasm"
version = "0.1.5"
authors = ["Ziyang Li"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
scallop-core = { path = "../../core" }
getrandom = { version = "0.2", features = ["js"] }
